services:
  
  minio:
    image: quay.io/minio/minio
    container_name : minio
    ports: 
      - "9003:9003"
      - "9000:9000"
    environment:
      - MINIO_ROOT_USER=root
      - MINIO_ROOT_PASSWORD=qwertyuiop
      # - MINIO_SERVER_URL=http://localhost:9004


    volumes:
      - .miniodata:/data
    command: server /data --console-address ":9003"